routes/web.php
<?php

use App\Http\Controllers\ReportController;
use App\Http\Controllers\SeedTMDBController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PageController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\UserProfileController;
use App\Http\Controllers\ResetPassword;
use App\Http\Controllers\ChangePassword;
use App\Http\Controllers\MovieAPIController;
use App\Http\Controllers\MovieController;
use App\Http\Controllers\MoviePlaylistController;
use App\Http\Controllers\SeedCountriesController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('get-languages', [SeedCountriesController::class, 'getLanguages']);
Route::get('seed-movies', [SeedTMDBController::class, 'seedMovies']);
Route::get('seed-genres', [SeedTMDBController::class, 'seedGenres']);
Route::get('seed-movie-genres', [SeedTMDBController::class, 'seedMovieGenres']);

Route::get('/export/users/pdf', [ReportController::class, 'export_users_pdf'])->name('export.users.pdf')->middleware('auth');
Route::get('/export/users/excel', [ReportController::class, 'export_users_excel'])->name('export.users.excel')->middleware('auth');
Route::resource('user', UserController::class)->middleware('auth');
Route::resource('movie', MovieController::class)->middleware('auth');
Route::resource('playlist', MoviePlaylistController::class)->middleware('auth');
Route::get('monthly-release-trend/{year}', [MovieAPIController::class, 'monthlyReleaseTrend'])->middleware('auth');
Route::get('movie-list', [MovieController::class, 'movie_list'])->middleware('auth');
Route::get('load-more-movies', [MovieController::class, 'loadMoreData'])->name('load.more.movies');
Route::get('load-more-playlists', [MoviePlaylistController::class, 'loadMoreData'])->name('load.more.playlists');
Route::get('get-movie/{movie_id}', [MovieController::class, 'getMovie']);
Route::get('get-playlist/{playlist_id}', [MoviePlaylistController::class, 'getPlaylist']);

Route::get('/', function () { return redirect('/dashboard'); })->middleware('auth');

Route::get('/register', [RegisterController::class, 'create'])->middleware('guest')->name('register');
Route::post('/register', [RegisterController::class, 'store'])->middleware('guest')->name('register.perform');
Route::get('/login', [LoginController::class, 'show'])->middleware('guest')->name('login');
Route::post('/login', [LoginController::class, 'login'])->middleware('guest')->name('login.perform');
Route::get('/reset-password', [ResetPassword::class, 'show'])->middleware('guest')->name('reset-password');
Route::post('/reset-password', [ResetPassword::class, 'send'])->middleware('guest')->name('reset.perform');
Route::get('/change-password', [ChangePassword::class, 'show'])->middleware('guest')->name('change-password');
Route::post('/change-password', [ChangePassword::class, 'update'])->middleware('guest')->name('change.perform');

Route::get('/dashboard', [HomeController::class, 'index'])->name('home')->middleware('auth');
Route::group(['middleware' => 'auth'], function () {
    Route::get('/virtual-reality', [PageController::class, 'vr'])->name('virtual-reality');
    Route::get('/rtl', [PageController::class, 'rtl'])->name('rtl');
    Route::get('/profile', [UserProfileController::class, 'show'])->name('profile');
    Route::post('/profile', [UserProfileController::class, 'update'])->name('profile.update');
    Route::get('/profile-static', [PageController::class, 'profile'])->name('profile-static');
    Route::get('/sign-in-static', [PageController::class, 'signin'])->name('sign-in-static');
    Route::get('/sign-up-static', [PageController::class, 'signup'])->name('sign-up-static');
    Route::get('/{page}', [PageController::class, 'index'])->name('page');
    Route::post('logout', [LoginController::class, 'logout'])->name('logout');
});

app/Http/Controllers/MoviePlaylistController.php
<?php

namespace App\Http\Controllers;

use App\Models\Genre;
use App\Models\Playlist;
use Illuminate\Http\Request;

class MoviePlaylistController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        $playlists = Playlist::query();
        $playlists = $this->filter($request, $playlists);
        $playlists = $playlists->orderBy('id', 'ASC')->paginate(8);

        $genres = Genre::orderBy('name')->get();

        return view('movie-playlist.index', compact('playlists', 'request', 'genres'));
    }

    public function getPlaylist($id)
    {
        $playlist = Playlist::with('movies')->with('creator')->find($id);
        $movies = $playlist->movies;

        $playlist['creator_name'] = $playlist->creator->name;

        return response()->json($playlist);
    }

    public function filter($request, $playlists)
    {
        if ($request->original_title) {
            $playlists = $playlists->whereRelation('movies', 'original_title', 'LIKE', '%' . $request->original_title . '%');
        }

        if ($request->genre) {
            $playlists = $playlists->whereRelation('movies.genres', 'genres.id', $request->genre);
        }

        return $playlists;
    }
}

resources/views/movie-playlist/index.blade.php
@extends('layouts.app')

@section('content')
    @include('layouts.navbars.auth.topnav', ['title' => 'Playlist'])
    <div class="row mt-4 mx-4">
        <div class="col-12">
            @if (session()->has('status'))
                <div class="alert alert-light" role="alert">
                    {{ session('message') }}
                </div>
            @endif

            <div class="card mb-4">
                <div class="card-header pb-0">
                    <h6 class="mb-0">Search</h6>
                </div>
                <div class="card-body pt-0 pb-2">
                    <form action="{{ route('playlist.index') }}" method="GET">
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="original_title" class="form-control-label">Movie Title</label>
                                    <input class="form-control" type="text" id="original_title" name="original_title" value="{{ old('original_title', $request->original_title) }}">
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="example-text-input" class="form-control-label">Genre</label>
                                    <select class="form-control" id="genre" class="genre" name="genre" style="width: 100%" >
                                        <option value="">Please Choose</option>

                                        @foreach ($genres as $genre)
                                            <option value="{{ $genre->id }}" @selected($genre->id == $request->genre)>{{ $genre->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary btn-sm ms-auto">Search</button>
                    </form>
                </div>
            </div>

            <div class="card mb-4">
                <div class="card-header pb-0">
                    <h6>Playlist</h6>
                    {{-- <div class="d-flex align-items-center">
                            <a href="{{ route('movie.create') }}" class="btn btn-primary btn-sm mx-1">Add New Movie</a>

                    </div> --}}
                </div>
                <div class="card-body px-0 pt-0 pb-2">
                    <div class="row" id="items_container">
                        @foreach ($playlists as $playlist)
                        <div class="col-md-3 mt-4">
                            <div class="card">
                              <img class="card-img-top" src="{{ $playlist->getMostPopularPoster() }}">
                              <div class="card-body">
                                <h6>
                                    {{ $playlist->title }}
                                </h6>
                                <p class="text-truncate">
                                    {{ $playlist->description }}
                                </p>
                                {{-- <a href="javascript:;" class="text-primary icon-move-right">More about us
                                  <i class="fas fa-arrow-right text-xs ms-1" aria-hidden="true"></i>
                                </a> --}}
                                <a href="" class="pe-2" data-bs-toggle="modal"
                                    data-bs-target="#playlistModal" id="playlistModalButton"
                                    data-id="{{ $playlist->id }}">
                                    <i class="fa fa-solid fa-eye"></i> More info
                                </a>
                              </div>
                            </div>
                          </div>
                        @endforeach
                    </div>

                    @if($playlists->count() == 8)
                    <div class="col-md-12 mt-4 text-center">
                            <button id="load_more_button" data-page="{{ $playlists->currentPage() + 1 }}"
                                class="btn btn-primary btn-lg btn-block">Load More</button>
                    </div>
                    @endif
                </div>
                @include('movie-playlist.playlist-modal')
            </div>
        </div>
    </div>
@endsection

@push('after-scripts')
<script>
    $(document).ready(function() {
        $('#genre').select2();

        function fetchData() {
          return new Promise((resolve, reject) => {
            url = "{{ url('/load-more-playlists/') }}";
            fetch(url + "?start=" + start + "&" + location.search.substr(1)) // Example API endpoint
              .then(response => {
                if (!response.ok) {
                  throw new Error('Something is wrong.');
                }
                return response.json();
              })
              .then(data => {
                resolve(data); // Resolve with the fetched data
              })
              .catch(error => {
                reject(error); // Reject with the encountered error
              });
          });
        }

        var start = 8;

        $('#load_more_button').click(function() {
            // Using the fetchData function
            fetchData()
              .then(data => {
                // Handle the fetched data asynchronously
                if (data.data.length > 0) {
                    var html = '';
                    for (var i = 0; i < data.data.length; i++) {
                        html += `<div class="col-md-3 mt-4">
                            <div class="card">
                              <img class="card-img-top" src="` + data.data[i].poster_path + `">
                              <div class="card-body">
                                <h4>
                                    ` + data.data[i].original_title + `
                                </h4>
                                <p>
                                    ` + moment(data.data[i].release_date).format('D MMMM YYYY') + `
                                </p>
                                <a href="" class="pe-2" data-bs-toggle="modal"
                                    data-bs-target="#playlistModal" id="playlistModalButton"
                                    data-id="` + data.data[i].id + `">
                                    <i class="fa fa-solid fa-eye"></i> More info
                                </a>
                              </div>
                            </div>
                          </div>`;
                    }

                    //append data with fade in effect
                    $('#items_container').append($(html).hide().fadeIn(1000));
                    $('#load_more_button').html('Load More');
                    $('#load_more_button').attr('disabled', false);
                    start = data.next;
                    console.log(data.next);
                } else {
                    $('#load_more_button').html('No More Data Available');
                    $('#load_more_button').attr('disabled', true);
                }
                // Perform actions with the fetched data or update the DOM asynchronously
              })
              .catch(error => {
                // Handle errors if the promise is rejected
                console.error('Error fetching data:', error);
                // Perform error handling or display an error message asynchronously
              });

        });




        // var start = 8;

        // $('#load_more_button').click(function() {
        //     $.ajax({
        //         url: "{{ route('load.more.movies') }}",
        //         method: "GET",
        //         data: {
        //             start: start
        //         },
        //         dataType: "json",
        //         beforeSend: function() {
        //             $('#load_more_button').html('Loading...');
        //             $('#load_more_button').attr('disabled', true);
        //         },
        //         success: function(data) {
        //             if (data.data.length > 0) {
        //                 var html = '';
        //                 for (var i = 0; i < data.data.length; i++) {
        //                     html += `<div class="col-md-3 mt-4">
        //                         <div class="card">
        //                           <img class="card-img-top" src="` + data.data[i].poster_path + `">
        //                           <div class="card-body">
        //                             <h4>
        //                                 ` + data.data[i].original_title + `
        //                             </h4>
        //                             <p>
        //                                 ` + moment(data.data[i].release_date).format('D MMMM YYYY') + `
        //                             </p>
        //                             <a href="javascript:;" class="text-primary icon-move-right">More about us
        //                               <i class="fas fa-arrow-right text-xs ms-1" aria-hidden="true"></i>
        //                             </a>
        //                           </div>
        //                         </div>
        //                       </div>`;
        //                 }

        //                 //append data with fade in effect
        //                 $('#items_container').append($(html).hide().fadeIn(1000));
        //                 $('#load_more_button').html('Load More');
        //                 $('#load_more_button').attr('disabled', false);
        //                 start = data.next;
        //                  console.log(data.next);
        //             } else {
        //                 $('#load_more_button').html('No More Data Available');
        //                 $('#load_more_button').attr('disabled', true);
        //             }
        //         }
        //     });
        // });


        $('#reset-btn').click(function(event) {
            $("#username").val('');
            $("#kp").val('');
            $("#nama").val('');
        });

    });

</script>
@endpush

resources/views/movie-playlist/playlist-modal.blade.php
<div class="modal fade" id="playlistModal" tabindex="-1" role="dialog" aria-labelledby="playlistModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="playlistModalLabel"></h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-12">
                        <img id="modal_poster_path" style="max-width: 50%" src="" alt="">
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="modal_description">Description</label>
                            <p class="text-primary text-small ms-1" id="modal_description"></p>
                        </div>
                        <div class="form-group">
                            <label for="modal_creator">Created By</label>
                            <p class="text-primary text-small ms-1" id="modal_creator"></p>
                        </div>
                        <div class="form-group">
                            <label for="modal_total_movies">Number of Movies</label>
                            <p class="text-primary text-small ms-1" id="modal_total_movies"></p>
                        </div>
                    </div>
                </div>
                <div class="row" id="movies_container">
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn bg-gradient-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

@push('after-scripts')
    <script>
        $(document).ready(function() {
            const formatter = new Intl.NumberFormat('en-US', {
              style: 'currency',
              currency: 'USD',
            });

            $('body').on('click', '#playlistModalButton', function(event) {
                event.preventDefault();
                var id = $(this).data('id');
                $.get('/get-playlist/' + id,
                    function(data) {
                        console.log(data);
                        $('#playlistModalLabel').html(data.title);
                        $('#modal_description').html(data.description);
                        $('#modal_creator').html(data.creator_name);
                        $('#modal_total_movies').html(data.movies.length);

                        var html = '';
                        for (var i = 0; i < data.movies.length; i++) {
                            // console.log(data.movies);

                            html += `<div class="col-md-3 mt-4">
                                <div class="card">
                                  <img class="card-img-top" src="` + data.movies[i].poster_path + `">
                                  <div class="card-body">
                                    <h6>
                                        ` + data.movies[i].original_title + `
                                    </h6>
                                    <label class="ms-0">
                                        ` + moment(data.movies[i].release_date).format('D MMMM YYYY') + `
                                    </label>
                                  </div>
                                </div>
                              </div>`;


                        }
                        $('#movies_container').append($(html).hide().fadeIn(1000));

                    })

            });
        });
    </script>
@endpush